version: "3.9"

services:
    app:
      build: .
      command: bash -c "python manage.py migrate && python manage.py runserver"
      volumes:
        - .:/app
      ports:
        - 8000
      env_file: /djamgo_project/.env
      